# Generated by Django 5.0.6 on 2024-07-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aurio', '0003_watchlater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsongs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('song', models.FileField(upload_to='images')),
                ('movie', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
