# Generated by Django 5.0.6 on 2024-07-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aurio', '0004_tsongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tsongs',
            new_name='Tsong',
        ),
    ]
