# Generated by Django 5.0.6 on 2024-07-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aurio', '0005_rename_tsongs_tsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsong',
            old_name='image',
            new_name='timage',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='movie',
            new_name='tmovie',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='name',
            new_name='tname',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='singer',
            new_name='tsinger',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='song',
            new_name='tsong',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='song_id',
            new_name='tsong_id',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='tags',
            new_name='ttags',
        ),
    ]
