# Generated by Django 5.0.6 on 2024-07-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aurio', '0006_rename_image_tsong_timage_rename_movie_tsong_tmovie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsong',
            old_name='timage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='tmovie',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='tname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='tsinger',
            new_name='singer',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='tsong',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='tsong_id',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='tsong',
            old_name='ttags',
            new_name='tags',
        ),
    ]
