# Generated by Django 5.0.6 on 2024-07-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aurio', '0007_rename_timage_tsong_image_rename_tmovie_tsong_movie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tsong',
        ),
    ]
