# Generated by Django 5.0.6 on 2024-07-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aurio', '0011_oldsong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
